### PR TITLE
Joint state aggregator now also publishes velocities and efforts

### PR DESCRIPTION
**Pull request by svenschneider**
Previously the joint state aggregator only republished the joint positions that it received.

With the latest commit the joint velocities and efforts are included in the "joint_states_combined" topic as well.

### CODE REVIEW

**Comment by floweisshardt** [comment]
Thanks. I will test the code as soon as our robot is back in Stuttgart.

**Comment by floweisshardt** [comment]
Hi Sven, thanks for the pull request. I will integrate it as soon as our repository structure is fixed again after the restructure process.
-Florian

**Comment by svenschneider** [comment]
The latest commit allows to actively query the joint state by a service call.

Note: I have tested this version only with the Diamondback cob_head_axis package on our Care-O-bot.

**Comment by floweisshardt** [comment]
During our restructuring process we found out that the joint_state_aggregator is not required anymore because this feature is now provided by the joint_state_publisher (can now deal with multiple distributed joint_state messages). The problem with the mimic joint not supported by the joint_state_publisher directly is solved in the sdh driver, which publishes the joint_state separately now.

The querry joint_state service (if neccessary, see discussion on https://github.com/ipa-fmw/schunk_modular_robotics/pull/1) should be implemented in each driver component.

**Comment by svenschneider** [comment]
Thank you for the update.  Probably this pull request can be closed as well, when I have tried out the joint_states topic instead of the query service (also see the discussion linked above).

**Comment by svenschneider** [comment]
None of the requested changes is required anymore, so I will close the pull request.

**Pull request closed without merging**
